name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Ruby ${{ matrix.ruby }}${{ matrix.mn_threads == 1 && ' +MN' || '' }} ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.2.6'
          - '3.3.7'
          - '3.4.1'
          - 'head'
        os:
          - ubuntu-latest
          - macos-latest
        mn_threads: [0]

        include:
          - os: ubuntu-latest
            ruby: '3.4.1'
            mn_threads: 1
          - os: ubuntu-latest
            ruby: 'head'
            mn_threads: 1

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
      env:
        RUBY_MN_THREADS: ${{ matrix.mn_threads }}
